### ISSUE TITLE
Implementation of UMI feature

### ISSUE THREAD

**Issue by nwales** [grenaud/leeHom#12]
Hi Gabriel, I was exploring how to use leeHom's option to remove a "key" from paired-end reads, but I was unsuccessful. Would you mind clarifying how this feature is meant to work? In short, I have data with an 8bp index at the beginning of Read 1, and the reverse complement of it is observed just before the adapter in Read 2. You can see a schematic of it in Figure 1 of this publication: https://arxiv.org/pdf/1503.05074.pdf

I have tried to provide the known key for a given sample but the software fails to find the key. Without specifying a key, the software works as expected and recovers the insert with the ligated 8bp sequence. 

Is this the intention of the key trim feature or is it meant for something else? I can share two fastq files if it helps. 

All the best,
Nathan

**Comment by grenaud** [comment]
Hi Nathan,
Good to hear from you! Could you send me via email some examples? Can
you annotate the relevant portion separately i.e.
[key][sequence][adapter]?

cheers,

Gabriel
