### ISSUE TITLE
Update documentation to state unaligned bam IS required

### ISSUE THREAD

**Issue by jfy133** [grenaud/leeHom#15]
And a third one (sorry!), I started writing tests for the nf-core/module reported in #13 for leeHom version 1.2.15. 

~~The nf-core modules test data is highly minimal, and so I when I run with a BAM file of only 2 reads, it crashses with an error of `Could not open input BAM filetest.bam`~~

~~However I am still able to read the BAM file with `samtools view`. Therefore I'm not sure why leeHom can't open it. It would be nice to have more informative error messages as why it can't open the BAM file.~~

Side note: in your README you say the following:

```
# Does my BAM file have to be unmapped?
BAM files can also be used to store unmapped reads. Ideally, leehom should be used prior to mapping since reads will map to a more accurate location if the adapters have been removed and overlapping stretches have been merged.
```

however the `ideally` is confusing, as leeHom explicitly does NOT accept BAM files (you get an error message), so it might be worth answering this question in the README as just `Yes` (and then say you want to run it before mapping).

**Comment by jfy133** [comment]
Oops, samtools view default is SAM not BAM format 🤦‍♀, updated the issue accordingly

**Comment by grenaud** [comment]
done!
