### ISSUE TITLE
Can't set a random seed during read merging

### ISSUE THREAD

**Issue by longg2** [grenaud/leeHom#16]
Hi,

I've run into an issue where the way that leeHom resolves ties between basepairs during merging has lead to results not being reproducible between runs.

The crux of the problem lies in the function ```MergeTrimReads::randomGen()```. While it is quite understandable that at one point you'll need to break ties between nucleotides randomly, there's no ability for the user to set the seed to control _how_ these ties are solved. Instead we're only limited to the date and time that the program is run.

Could you insert an option to allow users to manually set the random seed, ensuring that the trimmed reads are reproducible between runs?

Thanks,

George

**Comment by grenaud** [comment]
dear george, i am on paternity leave and will get to this as soon as I
return.
