### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by apeltzer** [grenaud/leeHom#2]
Hi Gabriel,

me again ;-) . 
Can't get leeHom to compile on my mac unfortuantely. First compiled bamtools with cmake and then subsequently called make on leeHom:

`In file included from leeHom.cpp:12:
In file included from ./MergeTrimReads.h:22:
./leehom/leeHom/libgab/utils.h:860:17: warning: comparison of constant 18446744073709551615 with expression of type 'unsigned int' is always
      false [-Wtautological-constant-out-of-range-compare]
    if(posSlash == string::npos){
       ~~~~~~~~ ^  ~~~~~~~~~~~~
In file included from leeHom.cpp:12:
./MergeTrimReads.h:79:12: error: field has incomplete type 'char *[]'
    char*  chimInit[];/* = { */
           ^
3 warnings and 1 error generated.
make[1]: *** [leeHom.o] Error 1
make: *** [all] Error 2`

My GCC version:

`
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

**Comment by grenaud** [comment]
Hey Alex, good to hear from you! the variable chimInit was a legacy variable I should have deleted, it does not seem to have any use in the code anymore. I have also changed the unsigned in utils.h to a size_t. that should have been done to begin with. Tell me if your compiler complains.

**Comment by apeltzer** [comment]
Looks good - compiles and seems to run now! Thanks for the quick help ;-)

**Comment by grenaud** [comment]
There is also the new multicore version of leeHom, if you would like to try it.

**Comment by apeltzer** [comment]
Already on it :-)
