### ISSUE TITLE
output of leeHom

### ISSUE THREAD

**Issue by PeterParker1** [grenaud/leeHom#4]
Hi, Gabriel! I'm a postgraduate student from China. Today I used leeHom to process my raw data, and this is the command line 
leeHomMulti -t 16 -f AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -s AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -fq1 10_HFF2NALXX_L4_1.fq -fq2 10_HFF2NALXX_L4_2.fq -fqo 10
Finally I got 6 files, namely 10.fail.fq.gz, 10.fq.gz, 10_r1.fail.fq.gz, 10_r1.fq.gz, 10_r2.fail.fq.gz, 10_r2.fq.gz. This is a bit different from outputs of cutadapt. What I want to know is whether 10_r1.fq.gz and 10_r2.fq.gz are input for subsequent mapping to genome. And what do the other four files mean, especially 10.fq.gz ?
Thanks very much.

**Comment by grenaud** [comment]
Dear Peter, thak you for your interest in our work, I see your point this was not properly documented. I have added a section called "Interpreting the output using the fastq mode". I hope this is sufficiently clear/verbose. Let me know if this is acceptable and we will close the issue.

**Comment by PeterParker1** [comment]
OK, I will rerun the program with -v and --log. Thank you.

**Comment by PeterParker1** [comment]
Sorry, I misunderstood you meaning and I just found the section "Interpreting the output using the fastq mode" in the README.md file. I think [PREFIX].r1.fail.fq.gz and [PREFIX].r2.fail.fq.gz are files that shouldn't be used for mapping, because I ran fastqc and found the reads are adapter-contaminated and of low quality. Because [PREFIX].fail.fq is 0 byte, no fastqc check is done for it.

**Comment by grenaud** [comment]
Yes you can remove them from downstream analyses. Can I close the issue?

**Comment by PeterParker1** [comment]
Yes, please. Thanks a lot.

**Comment by grenaud** [comment]
no, thank you!
