### ISSUE TITLE
Compile Error MacOs

### ISSUE THREAD

**Issue by kokyriakidis** [grenaud/leeHom#6]
After the make command:

g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  utils.cpp -o utils.o
In file included from utils.cpp:1:0:
utils.h: In function 'std::string getCWD(char*)':
utils.h:1347:22: error: 'PATH_MAX' was not declared in this scope
     char actualpath [PATH_MAX+1];
                      ^
utils.h:1348:43: error: 'actualpath' was not declared in this scope
     char * returnRealpath = realpath(arg, actualpath);
                                           ^
utils.h: In function 'std::string getFullPath(const string&)':
utils.h:1377:22: error: 'PATH_MAX' was not declared in this scope
     char actualpath [PATH_MAX+1];
                      ^
utils.h:1378:51: error: 'actualpath' was not declared in this scope
     char * returnRealpath = realpath(stT.c_str(), actualpath);
                                                   ^
make: *** [utils.o] Error 1

What can I do?

**Comment by grenaud** [comment]
Dea kokyriakidis, thank you for reporting this issue, it seems an issue with libgab. I will investigate. What version of MacOS are you using?

**Comment by kokyriakidis** [comment]
MacOS Sierra 10.13.5

**Comment by grenaud** [comment]
Ok I am not a big macos guy but under Darwin Kernel 15.3.0, this variable is defined here:
/usr/include/sys/syslimits.h
However, I have added a failsafe compilation that defines PATH_MAX as being 1024, it seems to be the value on MacOS. 

I would go to the libgab/ directory, do:
`git status`
`git pull origin master`
`make clean`
`make`

then go back to leeHom/ and do a 
`make clean`
`make`

let me know if this works and I will close the ticket.

**Comment by kokyriakidis** [comment]
TONES OF ERRORS
++    -c -O3 -Wall -I../bamtools/include/ -I../bamtools/src/ -I../libgab -I../libgab/gzstream/   MergeTrimReads.cpp 
MergeTrimReads.cpp: In member function 'void MergeTrimReads::computeBestLikelihoodPairedEnd(const string&, const std::vector<int>&, const string&, const std::vector<int>&, const string&, const std::vector<int>&, const int&, const int&, const int&, double&, int&, int&, double&, int&, int&)':
MergeTrimReads.cpp:1343:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  indexAdapter<(2*maxLengthForPair-min_overlap_seqs);
              ^
/var/folders/bw/dpvcs2h51k7355d7w_81_dk40000gn/T//ccUILOUK.s:4:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
"virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from:
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in bamtools_fasta.cpp.o
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in bamtools_utilities.cpp.o
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libbamtools.a(SamHeader.cpp.o)
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libbamtools.a(SamFormatParser_p.cpp.o)
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libbamtools.a(SamFormatPrinter_p.cpp.o)
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libbamtools.a(SamHeaderValidator_p.cpp.o)
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libbamtools.a(BamMultiReader_p.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [leeHom] Error 1
make: *** [all] Error 2

**Comment by grenaud** [comment]
can you try deleting the whole directory, start from scratch and rebuild the software. In the bamtools directory, do you have:
build/src/toolkit/bamtools
and can you execute it?

**Comment by kokyriakidis** [comment]
Nothing happens and yes, I have bamtools and I can execute it

**Comment by kokyriakidis** [comment]
I updated my gcc and g++ compiler and it now works BUT it generates warnings. See bellow the log

MacBook-Pro-toutes-Konstantinos:src kokyriakidis$ make
rm -rf ../bamtools/
mkdir ../bamtools/
git clone --recursive https://github.com/pezmaster31/bamtools.git ../bamtools/
Cloning into '../bamtools'...
remote: Counting objects: 4857, done.
remote: Total 4857 (delta 0), reused 0 (delta 0), pack-reused 4857
Receiving objects: 100% (4857/4857), 6.06 MiB | 754.00 KiB/s, done.
Resolving deltas: 100% (3373/3373), done.
cd ../bamtools/ && mkdir -p build/  && cd build/ && cmake .. && make && cd ../..
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'jsoncpp>=1'
Found system JsonCpp, not using bundled version
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kokyriakidis/Desktop/leeHom/bamtools/build
Scanning dependencies of target SharedHeaders
[  0%] Built target SharedHeaders
Scanning dependencies of target APIHeaders
[  0%] Built target APIHeaders
Scanning dependencies of target AlgorithmsHeaders
[  0%] Built target AlgorithmsHeaders
Scanning dependencies of target BamTools
[  1%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  3%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
[  5%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o
[ 10%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o
[ 15%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o
[ 20%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o
[ 23%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 25%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o
[ 28%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o
[ 30%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o
[ 32%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o
[ 33%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 35%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 37%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 38%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
[ 40%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 42%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
[ 44%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ByteArray_p.cpp.o
[ 45%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostAddress_p.cpp.o
[ 47%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostInfo_p.cpp.o
[ 49%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HttpHeader_p.cpp.o
[ 50%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ILocalIODevice_p.cpp.o
[ 52%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/RollingBuffer_p.cpp.o
[ 54%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocket_p.cpp.o
[ 55%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 57%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 59%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatParser_p.cpp.o
[ 61%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 62%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 64%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/utils/BamException_p.cpp.o
[ 66%] Linking CXX static library libbamtools.a
[ 66%] Built target BamTools
Scanning dependencies of target BamTools-utils
[ 67%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_fasta.cpp.o
[ 69%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_options.cpp.o
[ 71%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_pileup_engine.cpp.o
[ 72%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_utilities.cpp.o
[ 74%] Linking CXX static library libbamtools-utils.a
[ 74%] Built target BamTools-utils
Scanning dependencies of target bamtools_cmd
[ 76%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_convert.cpp.o
[ 77%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_count.cpp.o
[ 79%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_coverage.cpp.o
[ 81%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_filter.cpp.o
In file included from /Users/kokyriakidis/Desktop/leeHom/bamtools/src/toolkit/bamtools_filter.cpp:19:
In file included from /usr/local/Cellar/jsoncpp/1.8.4/include/json/json.h:10:
/usr/local/Cellar/jsoncpp/1.8.4/include/json/value.h:404:3: warning: explicit conversion functions are a C++11 extension [-Wc++11-extensions]
  explicit operator bool() const;
  ^~~~~~~~
1 warning generated.
[ 83%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_header.cpp.o
[ 84%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_index.cpp.o
[ 86%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_merge.cpp.o
[ 88%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_random.cpp.o
[ 89%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
[ 91%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_revert.cpp.o
[ 93%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_sort.cpp.o
[ 94%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_split.cpp.o
[ 96%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_stats.cpp.o
[ 98%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools.cpp.o
[100%] Linking CXX executable bamtools
[100%] Built target bamtools_cmd
rm -rf libgab/
git clone --recursive https://github.com/grenaud/libgab.git ../libgab/
Cloning into '../libgab'...
remote: Counting objects: 285, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 285 (delta 4), reused 5 (delta 1), pack-reused 271
Receiving objects: 100% (285/285), 121.82 KiB | 234.00 KiB/s, done.
Resolving deltas: 100% (174/174), done.
make -C ../libgab
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  utils.cpp -o utils.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  testUtils.cpp -o testUtils.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
make -C gzstream/
g++    -I. -O -c -o gzstream.o gzstream.C
ar cr libgzstream.a gzstream.o
g++   -o testUtils testUtils.o utils.o gzstream/libgzstream.a -lz
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  ReconsReferenceBAM.cpp -o ReconsReferenceBAM.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  PutProgramInHeader.cpp -o PutProgramInHeader.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  FastQObj.cpp -o FastQObj.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  FastQParser.cpp -o FastQParser.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++  -Wall  -lm -O3 -I. -Igzstream/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/include/ -I/Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/include/  -c  testRecons.cpp -o testRecons.o
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
g++   -o testRecons testRecons.o utils.o /Users/kokyriakidis/Desktop/leeHom/bamtools/build/src/api/libbamtools.a ReconsReferenceBAM.o gzstream/libgzstream.a -lz
g++    -c -O3 -Wall -I../bamtools/include/ -I../bamtools/src/ -I../libgab -I../libgab/gzstream/   MergeTrimReads.cpp 
g++    -c -O3 -Wall -I../bamtools/include/ -I../bamtools/src/ -I../libgab -I../libgab/gzstream/   leeHom.cpp 
g++    -o leeHom leeHom.o MergeTrimReads.o ../libgab/PutProgramInHeader.o ../libgab/FastQObj.o ../libgab/FastQParser.o ../libgab/gzstream/libgzstream.a ../bamtools/build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o ../bamtools/build/src/api/libbamtools.a ../libgab/utils.o  -lm -lz  -lpthread 
g++    -c -O3 -Wall -I../bamtools/include/ -I../bamtools/src/ -I../libgab -I../libgab/gzstream/   leeHomMulti.cpp 
leeHomMulti.cpp:1685:8: warning: unused variable 'queueSize' [-Wunused-variable]
                        int queueSize = int(queueDataToprocessFQ.size());
                            ^
leeHomMulti.cpp:2062:8: warning: unused variable 'queueSize' [-Wunused-variable]
                        int queueSize = int(queueDataToprocess.size());
                            ^
2 warnings generated.
g++    -o leeHomMulti leeHomMulti.o MergeTrimReads.o ../libgab/PutProgramInHeader.o ../libgab/FastQObj.o ../libgab/FastQParser.o ../libgab/gzstream/libgzstream.a ../bamtools/build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o ../bamtools/build/src/api/libbamtools.a ../libgab/utils.o  -lm -lz  -lpthread

**Comment by grenaud** [comment]
warnings are fine :-) Thank you for reporting this, I was at a loss as to how to fix this. Can I close the ticket?

**Comment by kokyriakidis** [comment]
Yes, you can close it. Thank you very much!
