### ISSUE TITLE
leehom parameters

### ISSUE THREAD

**Issue by kokyriakidis** [grenaud/leeHom#7]
Hello! 
I read a paper and it uses leehom as adapter trimming and merging. I states:
```
Sequences were adapter-trimmed and filtered for adapter dimers and chimeras using
scripts included in leeHom [30]. Reads with more than 5 bases with quality scores
below 15 (PHRED-scale) were discarded. If the forward and reverse reads overlapped
for more than 11 bp, the two reads were merged. For the overlapping part, a consensus
sequence was determined by calling the base with the highest quality score.
Additionally, resulting merged reads that were shorter than 60 bp were discarded.
```
My question is: Where can I set these parameters?

**Comment by grenaud** [comment]
I assume you are talking about the kiwi paper. The "Reads with more than 5 bases with quality scores
below 15 (PHRED-scale) were discarded." and "resulting merged reads that were shorter than 60 bp were discarded." were both done using a different program, you cannot do this in leeHom.

For "If the forward and reverse reads overlapped for more than 11 bp, the two reads were merged."
this is an internal hard-coded parameter that I do not suggest modifying unless you know what you want to achieve. You could always spot it in the code, rebuild and use it.

**Comment by kokyriakidis** [comment]
And a question about the output. After the leeHom script I should use the merged file AND the r1+r2 files?

**Comment by grenaud** [comment]
yes but map them separately, the merged as single-end and the output r1+r2 as paired.
