### ISSUE TITLE
fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by GeegC** [grenaud/leeHom#8]
Hi,

I am having some problems installing leeHom.  When I run the Makefile I get the following error:

```
/home/georgia/bin/leeHom-master/bamtools/src/api/internal/io/BgzfStream_p.cpp:20:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
src/api/CMakeFiles/BamTools.dir/build.make:374: recipe for target 'src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o' failed
make[4]: *** [src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o] Error 1
make[4]: Leaving directory '/home/georgia/bin/leeHom-master/bamtools/build'
CMakeFiles/Makefile2:236: recipe for target 'src/api/CMakeFiles/BamTools.dir/all' failed
make[3]: *** [src/api/CMakeFiles/BamTools.dir/all] Error 2
make[3]: Leaving directory '/home/georgia/bin/leeHom-master/bamtools/build'
Makefile:129: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/georgia/bin/leeHom-master/bamtools/build'
Makefile:38: recipe for target '../bamtools/build/src/api/libbamtools.a' failed
make[1]: *** [../bamtools/build/src/api/libbamtools.a] Error 2
make[1]: Leaving directory '/home/georgia/bin/leeHom-master/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

I have the zlib1g-dev ubuntu package installed and I have the zlib.h file at /usr/include/zlib.h

Please can you let me know if there's another setting I need to change?  Thanks very much for your help.

**Comment by grenaud** [comment]
Hello! Thanks for bringing this to my attention. I want to be sure that I
understand. Does bamtools build but not leeHom or you cannot even get
bamtools to build?

Gabriel

GeegC <notifications@github.com> schrieb am Di., 18. Sep. 2018 16:17:

**Comment by GeegC** [comment]
Hi Gabriel,

Thanks very much for replying so quickly.  I think it fails while it is building BamTools and before it starts trying to build leeHom - but I'm not sure how to build BamTools only.

I am pretty sure it is failing on the "#include <zlib.h>" line in leeHom-master/bamtools/src/api/internal/io/BgzfStream_p.cpp

Thank you!

**Comment by grenaud** [comment]
What if you were to try to build bamtools itself, does it work? If so,
which commands have you used?

GeegC <notifications@github.com> schrieb am Di., 18. Sep. 2018 17:31:

**Comment by GeegC** [comment]
Hi Gabriel,

Thanks very much.  I also can't build bamtools using the instructions from it's github repo (from pezmaster31) - it fails in the same way.  But I do have the latest conda version of bamtools - can leeHom use that instead?

Thanks.

**Comment by grenaud** [comment]
I haven't packaged leeHom on bioconda yet. bamtools builds without problem
for me. Which distribution are you using?

Gabriel

**Comment by GeegC** [comment]
Ah - I think I've figured it out - it was trying to use the conda version of zlib rather than the system version - I disabled conda and managed to get it to install!  Thanks very much for your help.
