### ISSUE TITLE
meet with this error message while making binary

### ISSUE THREAD

**Issue by kaine1973** [grenaud/leeHom#9]
centOS6-final
I googled, and was told that I need this "libstdc++-static" . but this lib seems doesn't support centOS6 

`[root@master leeHom]# make`
`make -C src`
`make[1]: Entering directory '/home/Lab/src/leeHom_test/leeHom/src`
`g++    -o leeHom leeHom.o MergeTrimReads.o ../libgab/PutProgramInHeader.o ../libgab/FastQObj.o` `../libgab/FastQParser.o ../libgab/gzstream/libgzstream.a`
`../bamtools/build/src/utils/CMakeFiles/BamTools-utils.dir/*cpp.o`
`../bamtools/build/src/api/libbamtools.a`
`../libgab/utils.o  -lm -lz  -lpthread`
`/src/Anaconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz `
`collect2: error: ld returned 1 exit status`   
`make[1]: *** [Makefile:19: leeHom] Error 1`                                              
`make[1]: Leaving directory '/home/Lab/src/leeHom_test/leeHom/src`
`make: *** [Makefile:2: all] Error 2`

 this error doesn't happen on CentOS7. after I make this binary , I copyed it to my CentOS6 , still doesn't work, shows: 
`src/leeHomMulti: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by src/leeHomMulti)`

**Comment by grenaud** [comment]
Dear Kaine1973, thank you for reporting this. Have you tried installing zlib zlib-devel zlib-static:
` # yum install zlib zlib-devel zlib-static
`

Does this work?

**Comment by kaine1973** [comment]
Thanks for reply...
Same error...

**Comment by kaine1973** [comment]
The first time I tried make,  It said :
     "Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11")"
then, the gzstream.h shows , 
     gzstream/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
so I tried copy zlib.h to -I/path/include
     cp /usr/include/zconf.h libgab/gzstream/
     cp /usr/include/zlib.h libgab/gzstream/
make again:
     ld: cannot find -lz

**Comment by grenaud** [comment]
ok try `sudo yum install zlib*
`
If this does not work, I will post an executable on dropbox.

**Comment by grenaud** [comment]
has this worked for you kaine1973?

**Comment by kaine1973** [comment]
Didn’t work. I am sure I installed all zlib- . Error still happened when I ran a compiled binary from other machine.



________________________________
发件人: Gabriel Renaud <notifications@github.com>
发送时间: Thursday, November 29, 2018 6:55:54 PM
收件人: grenaud/leeHom
抄送: kaine1973; Author
主题: Re: [grenaud/leeHom] meet with this error message while making binary (#9)


has this worked for you kaine1973?

―

**Comment by grenaud** [comment]
Ok this is bizarre, you should be able to use the -lz flag. I will close the issue for now but it seems a local C++ problem.
